# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-14 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200713_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mTurkId', models.CharField(max_length=200)),
                ('groupId', models.CharField(max_length=200)),
                ('cameraPermitted', models.CharField(max_length=20)),
                ('recordDate', models.DateTimeField()),
            ],
        ),
    ]
